### ISSUE TITLE
Login template

### ISSUE THREAD

**Issue by squareZ** [contao-bootstrap/templates#5]
Hi,

the template of the login form is still default. Shouldn't it be just like the one for register?

And I don't know if it's only me, but I don't see the submit buttons as the bootstrap ones but as the default ones.

I'm using latest versions of this package and of course the latest stable release of Contao.

**Comment by dmolineus** [comment]
There could be a lot of templates being optimized for Bootstrap. At the moment there are only a few. 

So why is the register form already using the bootstrap theme? It's because of Contao has a **very, very inconsistent** way of handling and displaying forms. Some are hardcoded in templates, others are generated by the form widgets.

Contao-Bootstrap supports the form widget but does not provide much custom templates for the hardcoded stuff.

Feel free to provide some as pull request.

**Comment by squareZ** [comment]
> Feel free to provide some as pull request.

I just did it. But only for the version without table structure as I think tables are only for displaying information, not for layout and stuff.

**Comment by dmolineus** [comment]
Thanks, looks great so far! You mean latest version of Contao (3.4), right? 

That's basically okay, the only thing which should kept in mind that I support Contao 3.2 LTS so far, so usage of template inheritance and blocks does not work (not used in this template).

**Comment by squareZ** [comment]
> Thanks, looks great so far! You mean latest version of Contao (3.4), right?

Oh yes, of course. My fault. x)

And sorry for the huge editing, I'm very new to GitHub and I barely use it.

**Comment by dmolineus** [comment]
Implemented in 06b495d4e2cf6d187896b449528398e6364e564b. Thanks for your contribution!
